language: julia
os:
  - linux
julia:
  - nightly
notifications:
  email: false
before_install:
  - curl http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
  - sudo apt-get install -q gfortran mpich2 libmpich2-3 libmpich2-dev
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("MPI"); Pkg.build("MPI")'
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Elemental"); Pkg.test("Elemental")'
