sudo: required
dist: trusty

language: julia

notifications:
  email: false

os:
  - linux

julia:
  - 0.6
  - nightly

matrix:
  allow_failures:
    - julia: nightly

env:
  global:
    - PATH=/usr/lib/ccache/:$HOME/OpenMPI/bin:$PATH
    - FC=gfortran-5
  matrix:
    - MPI=mpich   CC=gcc-5     CXX=g++-5       CACHE_NAME=JOB1
    - MPI=mpich   CC=clang-3.8 CXX=clang++-3.8 CACHE_NAME=JOB2
    - MPI=openmpi CC=gcc-5     CXX=g++-5       CACHE_NAME=JOB3
    - MPI=openmpi CC=clang-3.8 CXX=clang++-3.8 CACHE_NAME=JOB4

cache:
  directories:
    - $HOME/.ccache

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        key_url: http://apt.llvm.org/llvm-snapshot.gpg.key
      - sourceline: 'ppa:dzombie/ccache'
    packages:
      - ccache
      - gcc-5
      - g++-5
      - gfortran-5
      - libstdc++-5-dev
      - clang-3.8

install:
  - echo `ccache -s`
  - sudo ln -s /usr/bin/ccache /usr/lib/ccache/clang-3.8
  - sudo ln -s /usr/bin/ccache /usr/lib/ccache/clang++-3.8
  - echo `which $CC`
  - echo `which $CXX`
  - curl https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
  - export CPU_CORES=2
  - sh ./mpi.sh $MPI > /dev/null
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Elemental")'
  - echo `ccache -s`

script:
  - julia --check-bounds=yes -e 'Pkg.test("Elemental")'
